export const actors = [
	'my cat',
	'my neighbor',
	'the coffee machine',
	'a mysterious stranger',
	'my houseplant',
	'the delivery driver',
	'my alarm clock',
	'a cosmic ray',
	'the wind',
	'my shadow',
	'the WiFi router',
	'a time traveler',
	'my reflection',
	'the mailman',
	'a dust bunny',
	'the dishwasher',
	'my conscience',
	'a squirrel',
	'the thermostat',
	'my phone charger',
	'the vacuum cleaner',
	'a butterfly',
	'my laptop',
	'the refrigerator',
	'a cloud',
	'the doorbell',
	'my keys',
	'a pigeon',
	'the washing machine',
	'my favorite mug',
	'the ceiling fan',
	'a spider',
	'my parking meter',
	'the microwave',
	'a paper clip',
	'the garbage disposal',
	'my inner voice',
	'a rubber duck',
	'the toaster',
	'my wallet',
	'the smoke detector',
	'a fortune cookie',
	'my pencil',
	'the air conditioner',
	'a rubber band',
	'the blender',
	'my shoelaces',
	'a sticky note',
	'the garage door',
	'my headphones',
	'the printer',
	'a stray sock',
	'my backpack',
	'the light switch',
	'a house gecko',
	'the elevator',
	'my lunch',
	'a random email',
	'the car keys',
	'my motivation',
];

export const circumstances = [
	'is currently investigating my criminal past',
	'has declared war on productivity',
	'is having an existential crisis',
	'refuses to acknowledge daylight saving time',
	"is convinced I'm a government spy",
	'has developed sentience and demands rights',
	'is on strike for better working conditions',
	'has joined a mime troupe',
	'is practicing interpretive dance',
	'has become a conspiracy theorist',
	'is writing a tell-all memoir',
	'has started a podcast about my failures',
	'is learning to juggle flaming objects',
	'has discovered the secret to time travel',
	'is busy solving world hunger',
	'has joined a mariachi band',
	'is competing in the Olympics of procrastination',
	'has become a professional napper',
	'is teaching philosophy to houseplants',
	'has started a revolution',
	'is busy rewriting the laws of physics',
	'has become a food critic',
	'is practicing for the world championship of hiding',
	'has discovered the meaning of life',
	'is busy calculating the probability of my success',
	'has started a support group',
	'is learning ancient languages',
	'has become a life coach for inanimate objects',
	'is busy organizing a flash mob',
	'has developed trust issues',
	'is competing in professional thumb wrestling',
	'has become a meditation guru',
	'is busy inventing new colors',
	'has started a cult of personality',
	'is practicing telepathic communication',
	'has become a stand-up comedian',
	'is busy solving the mysteries of the universe',
	'has joined witness protection',
	'is learning to speak dolphin',
	'has become a professional mourner',
	'is busy rewriting history',
	'has started a detective agency',
	'is practicing advanced origami',
	'has become a professional sleepwalker',
	'is busy teaching etiquette to zombies',
	'has started a happiness consulting firm',
	'is learning to communicate through interpretive dance',
	'has become a professional dreamer',
	'is busy organizing my sock drawer by emotional significance',
	'has started a campaign for universal napping rights',
	'is practicing for the world championship of overthinking',
	'has become a certified procrastination specialist',
	'is busy writing poetry about the futility of deadlines',
	'has started a business selling bottled motivation',
	'is learning to harness the power of cosmic laziness',
	'has become a professional excuse validator',
	'is busy inventing new forms of creative avoidance',
	'has started a support group for reformed overachievers',
	'is practicing the ancient art of strategic incompetence',
	'has become a motivational speaker for unmotivated people',
];
