export const JOKES = [
	{ emoji: '😂', quip: 'Laughter is the best medicine!' },
	{ emoji: '🤖', quip: 'Beep boop! Robots have feelings too.' },
	{ emoji: '🦄', quip: 'Always be yourself. Unless you can be a unicorn.' },
	{ emoji: '🐢', quip: 'Slow and steady wins the race.' },
	{ emoji: '🌮', quip: "Taco 'bout a good time!" },
	{ emoji: '🦥', quip: 'Take it slow, like a sloth.' },
	{ emoji: '🥑', quip: "Avocado-n't worry, be happy!" },
	{ emoji: '🐙', quip: 'Feeling tentacool today!' },
	{ emoji: '🦖', quip: "You're dino-mite!" },
	{ emoji: '🐸', quip: "It's not easy being green!" },
	{ emoji: '🌟', quip: "You're a star!" },
	{ emoji: '🍋', quip: 'When life gives you lemons, make lemonade!' },
	{ emoji: '🐱', quip: "You've got to be kitten me!" },
	{ emoji: '🌈', quip: 'After every storm comes a rainbow.' },
	{ emoji: '🦋', quip: 'Just wing it!' },
	{ emoji: '🐧', quip: 'Stay cool like a penguin!' },
	{ emoji: '🌻', quip: 'Turn your face to the sun!' },
	{ emoji: '🐝', quip: 'Bee happy!' },
	{ emoji: '🍓', quip: 'Berry nice to meet you!' },
	{ emoji: '🦊', quip: 'What does the fox say? Something clever!' },
	{ emoji: '🐵', quip: 'Monkey see, monkey do!' },
	{ emoji: '🍪', quip: "That's how the cookie crumbles!" },
	{ emoji: '🐳', quip: 'Have a whale of a time!' },
	{ emoji: '⚡', quip: "You're electrifying!" },
	{ emoji: '🐻', quip: 'Bear with me on this joke!' },
	{ emoji: '🍉', quip: "You're one in a melon!" },
	{ emoji: '🦉', quip: 'Owl always love you!' },
	{ emoji: '🐰', quip: 'Some bunny loves you!' },
	{ emoji: '🍣', quip: "You're on a roll!" },
	{ emoji: '🦆', quip: 'Duck, duck, goose!' },
	{ emoji: '🌊', quip: 'Go with the flow!' },
	{ emoji: '🐬', quip: "You're dolphinitely amazing!" },
	{ emoji: '🍌', quip: "You're bananas!" },
	{ emoji: '🦁', quip: "You're roaring with potential!" },
	{ emoji: '🌸', quip: 'Cherry blossom of happiness!' },
	{ emoji: '🐨', quip: 'Koala-ty time ahead!' },
	{ emoji: '🥨', quip: 'Life has its twists!' },
	{ emoji: '🍇', quip: 'Grape job!' },
	{ emoji: '🐺', quip: 'Howl are you doing?' },
	{ emoji: '🌵', quip: 'Stick with it!' },
	{ emoji: '🦒', quip: 'Stand tall like a giraffe!' },
	{ emoji: '🥕', quip: 'Orange you glad to see me?' },
	{ emoji: '🐯', quip: "You're grrreat!" },
	{ emoji: '🥔', quip: "You're one hot potato!" },
	{ emoji: '🐮', quip: "Holy cow, you're awesome!" },
	{ emoji: '🌷', quip: 'Tulip-tastic day!' },
	{ emoji: '🥞', quip: 'Stack up the good times!' },
	{ emoji: '🐊', quip: 'See you later, alligator!' },
	{ emoji: '🌲', quip: 'Tree-mendous effort!' },
	{ emoji: '🦜', quip: 'Polly wants a compliment!' },
	{ emoji: '🧀', quip: "You're grate!" },
	{ emoji: '🏔️', quip: 'You can move mountains!' },
	{ emoji: '🥯', quip: 'Everything bagel, everything possible!' },
	{ emoji: '🐕', quip: "You're pawsome!" },
	{ emoji: '🌹', quip: 'Stop and smell the roses!' },
	{ emoji: '🦓', quip: "You're unique in every stripe!" },
	{ emoji: '🍔', quip: "You're flippin' awesome!" },
	{ emoji: '🐤', quip: 'Tweet dreams!' },
	{ emoji: '🌞', quip: 'You brighten my day!' },
	{ emoji: '🍟', quip: 'Fry to be happy!' },
	{ emoji: '🏀', quip: 'Nothing but net!' },
	{ emoji: '🦋', quip: 'Transform like a butterfly!' },
	{ emoji: '🥖', quip: "You're the bread winner!" },
	{ emoji: '🐥', quip: "You're egg-cellent!" },
	{ emoji: '⭐', quip: 'Twinkle, twinkle, little star!' },
	{ emoji: '🦕', quip: 'Long story short...' },
	{ emoji: '🍭', quip: 'Sweet as candy!' },
	{ emoji: '🌋', quip: "You're lava-ly!" },
	{ emoji: '🦑', quip: 'Ink-credible job!' },
	{ emoji: '🐪', quip: 'Hump day happiness!' },
	{ emoji: '🥝', quip: "You're kiwi-t!" },
	{ emoji: '🐓', quip: "Don't count your chickens!" },
	{ emoji: '⚽', quip: 'Goal-oriented mindset!' },
	{ emoji: '🦒', quip: 'Reach for the stars!' },
	{ emoji: '🍊', quip: 'Orange you awesome!' },
	{ emoji: '🐸', quip: 'Hoppy to see you!' },
	{ emoji: '🥐', quip: "You're on a roll!" },
	{ emoji: '🐷', quip: 'Pig-ture perfect!' },
	{ emoji: '🎯', quip: 'Right on target!' },
	{ emoji: '🦅', quip: 'Soar like an eagle!' },
	{ emoji: '🥬', quip: 'Lettuce be friends!' },
	{ emoji: '🐹', quip: 'Wheel-y glad to know you!' },
	{ emoji: '🏆', quip: "You're a champion!" },
	{ emoji: '🦏', quip: 'Charge ahead!' },
	{ emoji: '🍡', quip: 'Sweet success!' },
	{ emoji: '🐛', quip: "Don't bug me, I'm awesome!" },
];
